# vim: set ts=2 sts=2 sw=2 expandtab:
version: '2'

services:
  mesos-slave:
    image: mesosphere/mesos-slave:1.7.1
    privileged: true
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: mesos,docker
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
      MESOS_FRAMEWORKS_HOME: /var/tmp/mesos/frameworks
      MESOS_IMAGE_PROVIDERS: docker
      MESOS_ISOLATION: filesystem/linux,docker/runtime
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

