on:
  schedule:
    - cron: '0 8 * * *'

name: Autobuild Docker image for criteo fork and push to repository
jobs:
  latest-version:
    name: Build and push new Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push new Docker image
        run: |
          GITHUB_REPO="criteo-forks/mesos"
          TAGS=`curl -u ${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_OAUTH_TOKEN }} https://api.github.com/repos/${GITHUB_REPO}/tags`
          export MESOS_GIT=https://github.com/${GITHUB_REPO}.git
          export MESOS_VERSION="`echo "$TAGS" | jq '.[].name' -r | sort -h | tail -n1`"
          echo "Current mesos version: ${MESOS_VERSION}"
          export DOCKER_REPO="criteo/mesosbuild"
          DOCKER_TAGS_URL="https://hub.docker.com/v2/repositories/${DOCKER_REPO}/tags?page_size=1000"
          if ! curl ${DOCKER_TAGS_URL} | jq -r '.results|.[]|.name' | grep -q "^$MESOS_VERSION\$"; then
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            ./build_and_push.sh
          else
            echo "Image already up to date on docker hub"
          fi
